version: "3.1"
services:
  db:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSRWORD: postgres
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      DEBUG: 1
      GMAIL_ID: "${GMAIL_ID}"
      GMAIL_PW: "${GMAIL_PW}"
