# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 13:29
from __future__ import unicode_literals

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='test_answer_file',
            field=models.FileField(default=1, upload_to=competition.models.user_competition_path),
            preserve_default=False,
        ),
    ]
